### PR TITLE
updates readme.md

### PR DESCRIPTION
**Pull request by rladstaetter**
fixes typo; adds a hint to help cmake find Qt

### CODE REVIEW

**Comment by miho** [comment]
Thanks for spotting the typo.

**Review by miho — COMMENTED** [review]
I would rather prefer consistent hints for CMake on Windows and Unix. Setting the prefix_path might work in this case but I prefer setting the Qt5_Dir. 

Can you try whether setting the Qt5_Dir works for you as well?

Thanks.

**Comment by rladstaetter** [comment]
i don‘t know why but setting Qt5_Dir didn‘t work for me. 😞

**Comment by miho** [comment]
Can you let me know your OS and the exact path you entered? Would like to fix this.

**Comment by miho** [comment]
and pls do a `ls` in the directory you entered. Then I'll try to reproduce it.

**Comment by rladstaetter** [comment]
ok, it was a false alarm, my bad, i just provided the wrong directory for 'Qt5_Dir'. 

I removed the superfluous entry concerning prefix_path, spotted another typo, added a hint for Qt5_Dir in the readme.md. 

also added an entry for ignoring .idea/ in .gitignore.

**Comment by rladstaetter** [comment]
i could compile nativefx-qt like described in the readme, just by providing the correct Qt5_Dir.

**Comment by miho** [comment]
Very cool. Thanks! Still would like to know your OS ;-) Linux or Mac?

**Comment by rladstaetter** [comment]
i've tested NativeFX with macOS Mojave 10.14.5 👍

**Pull request merged**
